# Generated by Django 6.0.1 on 2026-02-03 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kategori", "0001_initial"),
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produk",
            fields=[
                ("id_produk", models.BigAutoField(primary_key=True, serialize=False)),
                ("nama_produk", models.CharField(max_length=255)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kategori",
                        to="kategori.kategori",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="status.status",
                    ),
                ),
            ],
            options={
                "db_table": "produk",
            },
        ),
    ]
