# Generated by Django 6.0.1 on 2026-02-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kategori", "0001_initial"),
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id_status", models.BigAutoField(primary_key=True, serialize=False)),
                ("nama_produk", models.CharField(max_length=255)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "kategori_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kategori",
                        to="kategori.kategori",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to="status.status",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
