# Generated by Django 6.0.1 on 2026-02-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                ("id_kategori", models.BigAutoField(primary_key=True, serialize=False)),
                ("nama_kategori", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "kategori",
            },
        ),
    ]
