# Generated by Django 6.0.1 on 2026-02-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id_status", models.BigAutoField(primary_key=True, serialize=False)),
                ("name_status", models.CharField(verbose_name=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
