# Generated by Django 6.0.1 on 2026-02-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id_status", models.BigAutoField(primary_key=True, serialize=False)),
                ("nama_status", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "status",
            },
        ),
    ]
